name = "SvdUpdate"
uuid = "5197d5ce-7e41-4e8c-9a1e-8970cc3c81fb"
authors = ["Evan Ewing"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
